# Generated by Django 3.2.7 on 2021-09-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ribbon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ribbon',
            field=models.ManyToManyField(to='main_app.Ribbon'),
        ),
    ]
