# Generated by Django 3.2.7 on 2021-09-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pokemon_ribbon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='ribbon',
            new_name='ribbons',
        ),
    ]
